Grammarly fixes
robocorp/robocorp pull request #253
Opened 2024-02-19 14:50 UTC by kariharju

Linefeeds by writer in readme.md create havoc in docs -site side. When possible use VS Code Word Wrap when writing markdown to avoid manual linefeeds.

2024-02-20 15:07 UTC, cmin764 requested changes
LGTM given the content, but detected two other typos. (commented below)

Now given the line length, according to `markdownlint` [docs](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md013---line-length), a default line length of 80 chars is expected, but ofc, we can increase that.

What do you think @fabioz , shall we add a linter for the MDs we write/generate? Something that has a prettier preferably?

2024-02-20 15:07 UTC, cmin764 commented on browser/README.md
>  > - _action-package.yaml_ for an automation Action Packages
```suggestion
> - _action-package.yaml_ for automation Action Packages
```

2024-02-20 15:07 UTC, cmin764 commented on windows/README.md
>  > - _action-package.yaml_ for an automation Action Packages
```suggestion
> - _action-package.yaml_ for automation Action Packages
```

2024-02-21 16:32 UTC, cmin764 commented
This may look blocked now by this issue: https://github.com/robocorp/robocorp/issues/257

But to unblock it, maybe we should manually edit these files to match what we would achieve with the solution above, then merge it as it is without staying blocked until the solution is ready.

⚠️ What I still don't understand, is why our docs site rendering part isn't compatible with the Markdown suggested [format & rules](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md013---line-length) or why this started to become a problem today when we wrote line breaks in _.md_ files the entire time? Isn't this a problem that should be treated on the [**documentation**](https://github.com/robocorp/documentation) side, as long as we enforce a commonly accepted code-driven standard here in **robocorp**?

2024-03-15 08:42 UTC, kariharju commented
The length rule is not a markdown rule, just a markdown linter rule.
The docs rendering is only breaking if there are extra spaces, and the only way to get that is to manually add linefeeds.

Markdown is not code, it is content to applying old code styling rules on it really does not make sense. Markdown will in all cases (except looking at raw data in a text editor) be shown in whatever width layout so applying a some limit in the source file really does not help. 

Need to get these fixes in and let's look at the #257 separately.

2024-03-29 09:00 UTC, cmin764 commented
Will refactor this PR by applying this Notion [proposal](https://www.notion.so/robocorptechnologies/Markdown-fff71182e16d441b8599a40266ec9cc8?pvs=4#855177f5d45145adafa56c36ed8a29a0).

2024-03-29 16:11 UTC, merged