Format action output in local action server UI
robocorp/robocorp pull request #313
Opened 2024-03-26 21:16 UTC by custompointofview

Formatting result for the code mirror editor to show returns correctly. Some small stylisation to the Run drawer

- Changed 'Run' to 'Execute Action' & 'Executing' while in progress
- Added icon to button
- Formatted result string
- Added result type alongside the 'Result' header

![image](https://github.com/robocorp/robocorp/assets/10797145/c0fc1878-2128-4160-bef2-420cf8259905)

![image](https://github.com/robocorp/robocorp/assets/10797145/63fc3499-d3da-4643-9ce3-1e9821f14fb8)
![image](https://github.com/robocorp/robocorp/assets/10797145/572d2d1c-9312-40c8-88f3-c6bc13bffaa7)
![image](https://github.com/robocorp/robocorp/assets/10797145/45b8c1ca-45b4-4f96-8b00-016029dcef73)

2024-03-27 19:08 UTC, fabioz requested changes

2024-03-27 19:08 UTC, fabioz commented on action_server/frontend/src/views/actions/components/ActionRunResult.tsx
> +        <Header.Title title={outputSchemaType ? `Result (${outputSchemaType.type})` : 'Result'} />
I'm not sure about the `outputSchemaType.type` here. 
I think that on the cases the schema is simple (such as string, number, boolean) it works, but in bigger schemas it doesn't look ideal... Have you tested how it looks with a big schema (say a custom pydantic model with multiple fields)?

2024-03-27 19:08 UTC, fabioz commented on action_server/frontend/src/views/actions/components/ActionRun.tsx
> +          outputSchemaType={JSON.parse(action.output_schema) as { type: string }}
I think that the output schema could be an object when using a custom output model (pydantic)... I'm not sure it can be casted as string here (should be tested).

2024-03-28 08:51 UTC, custompointofview commented
@fabioz here is what happens when the following object is returned:
```
class Prospect(BaseModel):
    name: Annotated[str, Field(description="User's first name")]
    last_name: Annotated[str, Field(description="User's first name")]
```

![image](https://github.com/robocorp/robocorp/assets/10797145/8eb05eca-90d3-4562-a486-b8248d97d54f)

2024-03-28 08:52 UTC, custompointofview commented on action_server/frontend/src/views/actions/components/ActionRunResult.tsx
> +        <Header.Title title={outputSchemaType ? `Result (${outputSchemaType.type})` : 'Result'} />
Tested this. Please have a look at the top level comment.

2024-03-28 08:52 UTC, custompointofview commented on action_server/frontend/src/views/actions/components/ActionRun.tsx
> +          outputSchemaType={JSON.parse(action.output_schema) as { type: string }}
Tested this. Please have a look at the top level comment.

2024-04-01 17:45 UTC, fabioz approved these changes

2024-04-02 16:07 UTC, merged